openapi: 3.0.3
info:
  title: PostHog actions domains API
  version: 1.0.0
  description: ''
tags:
- name: domains
paths:
  /api/organizations/{organization_id}/domains/:
    get:
      operationId: domains_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      security:
      - PersonalAPIKeyAuth:
        - organization:read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrganizationDomainList'
          description: ''
      x-explicit-tags:
      - core
    post:
      operationId: domains_create
      parameters:
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
        required: true
      security:
      - PersonalAPIKeyAuth:
        - organization:write
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDomain'
          description: ''
      x-explicit-tags:
      - core
  /api/organizations/{organization_id}/domains/{id}/:
    get:
      operationId: domains_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this domain.
        required: true
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      security:
      - PersonalAPIKeyAuth:
        - organization:read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDomain'
          description: ''
      x-explicit-tags:
      - core
    put:
      operationId: domains_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this domain.
        required: true
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
        required: true
      security:
      - PersonalAPIKeyAuth:
        - organization:write
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDomain'
          description: ''
      x-explicit-tags:
      - core
    patch:
      operationId: domains_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this domain.
        required: true
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOrganizationDomain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOrganizationDomain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOrganizationDomain'
      security:
      - PersonalAPIKeyAuth:
        - organization:write
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationDomain'
          description: ''
      x-explicit-tags:
      - core
    delete:
      operationId: domains_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this domain.
        required: true
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      security:
      - PersonalAPIKeyAuth:
        - organization:write
      responses:
        '204':
          description: No response body
      x-explicit-tags:
      - core
  /api/organizations/{organization_id}/domains/{id}/scim/logs/:
    get:
      operationId: domains_scim_logs_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this domain.
        required: true
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      responses:
        '200':
          description: No response body
      x-explicit-tags:
      - core
  /api/organizations/{organization_id}/domains/{id}/scim/token/:
    post:
      operationId: domains_scim_token_create
      description: Regenerate SCIM bearer token.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this domain.
        required: true
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
        required: true
      responses:
        '200':
          description: No response body
      x-explicit-tags:
      - core
  /api/organizations/{organization_id}/domains/{id}/verify/:
    post:
      operationId: domains_verify_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this domain.
        required: true
      - $ref: '#/components/parameters/OrganizationIdPath'
      tags:
      - domains
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrganizationDomain'
        required: true
      responses:
        '200':
          description: No response body
      x-explicit-tags:
      - core
components:
  schemas:
    PatchedOrganizationDomain:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        domain:
          type: string
          maxLength: 128
        is_verified:
          type: boolean
          description: Determines whether a domain is verified or not.
          readOnly: true
        verified_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        verification_challenge:
          type: string
          readOnly: true
        jit_provisioning_enabled:
          type: boolean
        sso_enforcement:
          type: string
          maxLength: 28
        has_saml:
          type: boolean
          description: Returns whether SAML is configured for the instance. Does not validate the user has the required license (that check is performed in other places).
          readOnly: true
        saml_entity_id:
          type: string
          nullable: true
          maxLength: 512
        saml_acs_url:
          type: string
          nullable: true
          maxLength: 512
        saml_x509_cert:
          type: string
          nullable: true
        has_scim:
          type: boolean
          description: Returns whether SCIM is configured and enabled for this domain.
          readOnly: true
        scim_enabled:
          type: boolean
        scim_base_url:
          type: string
          nullable: true
          readOnly: true
        scim_bearer_token:
          type: string
          nullable: true
          readOnly: true
    PaginatedOrganizationDomainList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationDomain'
    OrganizationDomain:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        domain:
          type: string
          maxLength: 128
        is_verified:
          type: boolean
          description: Determines whether a domain is verified or not.
          readOnly: true
        verified_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        verification_challenge:
          type: string
          readOnly: true
        jit_provisioning_enabled:
          type: boolean
        sso_enforcement:
          type: string
          maxLength: 28
        has_saml:
          type: boolean
          description: Returns whether SAML is configured for the instance. Does not validate the user has the required license (that check is performed in other places).
          readOnly: true
        saml_entity_id:
          type: string
          nullable: true
          maxLength: 512
        saml_acs_url:
          type: string
          nullable: true
          maxLength: 512
        saml_x509_cert:
          type: string
          nullable: true
        has_scim:
          type: boolean
          description: Returns whether SCIM is configured and enabled for this domain.
          readOnly: true
        scim_enabled:
          type: boolean
        scim_base_url:
          type: string
          nullable: true
          readOnly: true
        scim_bearer_token:
          type: string
          nullable: true
          readOnly: true
      required:
      - domain
      - has_saml
      - has_scim
      - id
      - is_verified
      - scim_base_url
      - scim_bearer_token
      - verification_challenge
      - verified_at
  parameters:
    OrganizationIdPath:
      in: path
      name: organization_id
      required: true
      schema:
        type: string
      description: ID of the organization you're trying to access. To find the ID of the organization, make a call to /api/organizations/.
  securitySchemes:
    PersonalAPIKeyAuth:
      type: http
      scheme: bearer
x-tagGroups:
- name: All endpoints
  tags:
  - LLM Analytics
  - actions
  - activity_log
  - activity_logs
  - advanced_activity_logs
  - alerts
  - annotations
  - approval_policies
  - batch_exports
  - cdp
  - change_requests
  - code
  - code-invites
  - cohorts
  - comments
  - conversations
  - core
  - customer_analytics
  - customer_journeys
  - customer_profile_configs
  - dashboard_templates
  - dashboards
  - data_color_themes
  - data_modeling_jobs
  - data_warehouse
  - dataset_items
  - datasets
  - desktop_recordings
  - domains
  - early_access_feature
  - early_access_features
  - elements
  - endpoints
  - environments
  - error_tracking
  - evaluation_runs
  - evaluations
  - event_definitions
  - event_filter
  - event_schemas
  - events
  - experiment_holdouts
  - experiment_saved_metrics
  - experiments
  - exports
  - external_data_schemas
  - external_data_sources
  - feature_flags
  - file_system
  - file_system_shortcut
  - flag_value
  - groups
  - groups_types
  - health_issues
  - heatmap_screenshots
  - heatmaps
  - hog_flows
  - hog_function_templates
  - hog_functions
  - insight_variables
  - insights
  - integrations
  - invites
  - js-snippet
  - legal_documents
  - lineage
  - live_debugger_breakpoints
  - llm_analytics
  - llm_prompts
  - llm_skills
  - logs
  - managed_viewsets
  - max
  - max_tools
  - mcp_server_installations
  - mcp_servers
  - mcp_store
  - mcp_tools
  - members
  - notebooks
  - oauth_applications
  - object_media_previews
  - organizations
  - persisted_folder
  - persons
  - platform_features
  - plugin_configs
  - product_analytics
  - product_tours
  - project_secret_api_keys
  - projects
  - property_definitions
  - proxy_records
  - public_hog_function_templates
  - query
  - replay
  - reverse_proxy
  - role_external_references
  - roles
  - sandbox-environments
  - sandbox_environments
  - saved
  - schema_property_groups
  - sdk_doctor
  - session_group_summaries
  - session_recording_playlists
  - session_recordings
  - session_summaries
  - sessions
  - signals
  - subscriptions
  - surveys
  - taggers
  - task-automations
  - task-runs
  - task_automations
  - tasks
  - uploaded_media
  - user_home_settings
  - user_interviews
  - users
  - visual_review
  - warehouse_dag
  - warehouse_model_paths
  - warehouse_saved_queries
  - warehouse_saved_query_folders
  - warehouse_tables
  - warehouse_view_link
  - warehouse_view_links
  - web_analytics
  - web_experiments
  - web_vitals
  - welcome
  - workflows
